In [5]:
import collections
from multiprocessing import Pool
import pandas as pd
import numpy as np
import time

In [4]:
data = pd.read_csv('https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv')
data.reset_index(inplace=True) #Use idx as identifier
print(data.shape[0])
data.head()

150


index  sepal_length  sepal_width  petal_length  petal_width species
0      0           5.1          3.5           1.4          0.2  setosa
1      1           4.9          3.0           1.4          0.2  setosa
2      2           4.7          3.2           1.3          0.2  setosa
3      3           4.6          3.1           1.5          0.2  setosa
4      4           5.0          3.6           1.4          0.2  setosa

In [ ]:
### Divide into chunks of equal size 

In [14]:
## Define number of chunks
n = 10

In [37]:
def getIndices(data,n):
    dataSize = range(data.shape[0])
    chunksIdx = np.array_split(dataSize, n)
    return chunksIdx

def getRanges(array):
    return array[0],array[-1]

def subsetChunks(iterable,idxArray,idx):
    a,b = getRanges(idxArray[idx])
    return iterable[a:b]

In [36]:
arrayIdxChunks = getIndices(data,n)

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]),
 array([45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]),
 array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74]),
 array([75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89]),
 array([ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
        103, 104]),
 array([105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
        118, 119]),
 array([120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134]),
 array([135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
        148, 149])]

In [41]:
### Make iterable
iterData = list(data.itertuples())

In [42]:
### Create a dictionary of chunk
chunkedData = {_+1 : subsetChunks(iterData,arrayIdxChunks,_) for _ in range(len(arrayIdxChunks))}

In [ ]:
### break into chunks by the indices

SyntaxError: invalid syntax (<ipython-input-34-13df359cb17d>, line 1)